In [2]:
import numpy as np


### basic array creation

In [4]:
arr=np.array([1,2,3,4])#this is array
arr

array([1, 2, 3, 4])

In [5]:
arr=np.array([1,2,3,4,'hello'])#array only allow same data type so it convert in one data type
arr

array(['1', '2', '3', '4', 'hello'], dtype='<U21')

In [ ]:
a=[1,2,3,4,"hello"]#this is list
a

[1, 2, 3, 4, 'hello']

In [7]:
l=[[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### array generation function

In [10]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [11]:
# arr=np.zeros((4,6)) # it creates matrices of 4 rows and 6 coulumns and to identify it that it is matrices see two square braces in output
arr


array([1, 3, 5, 7, 9])

In [12]:
arr=np.linspace(1,5,10)#this creates  arrangement of 10 no. b/w 1 and 5 with same gape
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [13]:
arr=np.linspace(0,1,100)
arr


array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [ ]:
### random generation function

In [15]:
np. random.rand(10)# it gives output b/w 0 and 1


array([0.70103814, 0.81548682, 0.83235213, 0.58659488, 0.20121112,
       0.54595379, 0.66609056, 0.92108462, 0.75765904, 0.6433829 ])

In [16]:
np. random.randn(10)# it gives output b//w -3 and 3


array([ 1.46259639, -0.86190562,  0.88887759,  1.20016364,  0.08759923,
        0.80579166, -0.22368945,  0.84514432, -0.73359955,  0.63278151])

In [17]:
np. random.randint(6)#this generates a random no. b/w 0 and 6

1

In [18]:
np. random.randint(1,9)#this generates a random no. b/w 1 and 9

3

In [19]:
np. random.randint(1,20,6)#this generates a random no. b/w 1 and 9

array([13, 18,  8,  1,  7,  8], dtype=int32)

In [ ]:
#To make array by different ways
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
arr=np.arange(1,21,2)
print(arr)
arr=np.random.randint(100,233,4)
print(arr)
arr=np.random.rand(2,3,2)
print(arr)
arr=np.ones(4)
print(arr)
arr=np.zeros(4)
print(arr)
arr=np.linspace(20,40,10)
print(arr)

### these are array attributes

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr.size

9

In [23]:
arr.shape

(3, 3)

In [24]:
arr.dtype

dtype('int64')

### these are array methods

In [26]:
arr.min()

np.int64(1)

In [27]:
arr.max()

np.int64(9)

In [28]:
arr.sum()

np.int64(45)

In [29]:
np.sum(arr,axis=0)#axis 0 means columns and for row write 1

array([12, 15, 18])

In [30]:
arr.mean()

np.float64(5.0)

In [31]:
arr.std()#it is standard deviation

np.float64(2.581988897471611)

In [32]:
arr.argmax() #indecs of max element

np.int64(8)

In [33]:
arr.argmin()#indecs of min elements

np.int64(0)

### reshaping and resizing

In [35]:
arr= np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [36]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [37]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

### array indexing and slicing


In [39]:
import numpy as np

### numpy indexing and slicing of vectors

In [41]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [42]:
arr[6]#indexing starts from 0 so 6 means 7th element

np.int64(17)

In [43]:
arr[1:5:2]#slicing [start:stop:step] it gives 2nd,4th element

array([12, 14])

In [44]:
arr_slice=arr[3::2]#it gives 4th element and then it gives alternate element
arr_slice

array([14, 16, 18, 20])

### numpy indexing and slicing of matrices

In [46]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [47]:
arr[0]#indexing starts from 0 so 0 means 1st row

array([1, 2, 3, 4, 5])

In [48]:
arr[3]#it gives 4th row

array([16, 17, 18, 19, 20])

In [49]:
arr[0,3]#it gives 1st row and 4th element

np.int64(4)

In [50]:
arr[0:3,1:3]#it gives 1st,2nd,3rd row and 2nd,3rd element

array([[ 2,  3],
       [ 7,  8],
       [12, 13]])

### boolean indexing

In [52]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [53]:
bool_index=arr%2==0#it gives true for even no. and false for odd no.
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [54]:
arr=arr[bool_index]
arr

array([12, 14, 16, 18, 20])

In [55]:
### array operations

In [56]:
import numpy as np

### arithemetic operations

In [58]:
a1=np.array([1,2,3,4])#whn we perform any operation on array it is performed element wise the size of both array should be same
a2=np.array([5,6,7,8])

In [59]:
a1+a2

array([ 6,  8, 10, 12])

In [60]:
a1-a2

array([-4, -4, -4, -4])

In [61]:
a1*a2

array([ 5, 12, 21, 32])

In [62]:
a1/a2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [63]:
a1//a2

array([0, 0, 0, 0])

In [64]:
if np.all(a1%a2==0):
    print("divisible")
else:
    print("not divisible")

not divisible


### Broadcasting

In [66]:
l=[10,20,30,40,50,60]
arr=np.array(l)

In [67]:
arr+10#it adds 10 to each element of array

array([20, 30, 40, 50, 60, 70])

In [68]:
j=np.arange(1,21).reshape(5,4)
j

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [69]:
j+10#it adds 10 to each element of array so that we can perform operation on array of different size and shape this is called broadcasting

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30]])

### deep copy and shallow copy

In [71]:
a=np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [72]:
slice=a[:5]#it gives 1st 5 element of array
slice

array([1, 2, 3, 4, 5])

In [73]:
slice[0]=100#it changes the value of 1st element of slice but it also changes the value of 1st element of array because slice is shallow copy of array
slice
print(a)

[100   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20]


In [74]:
slice+10#it adds 10 to each element of slice but it also adds 10 to each element of array because slice is shallow copy of array

array([110,  12,  13,  14,  15])

### matrix operations

In [76]:
mat1=np.array([[1,2,3],[4,5,6],[7,8,9]])
mat1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
mat2=np.array([[1,11,12],[13,14,15],[16,17,18]])
mat2

array([[ 1, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [112]:
np.intersect1d(mat1,mat2)

array([1])

In [79]:
mat1*mat2#it gives element wise multiplication

array([[  1,  22,  36],
       [ 52,  70,  90],
       [112, 136, 162]])

In [80]:
mat1@mat2#it gives matrix multiplication

array([[ 75,  90,  96],
       [165, 216, 231],
       [255, 342, 366]])

In [ ]:
np.dot(mat1,mat2)#it also gives matrix multiplication

array([[ 75,  90,  96],
       [165, 216, 231],
       [255, 342, 366]])

In [82]:
mat1.T#it gives transpose of matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

### stacking arrays

### you cannot stack arrays  and materices of different size and shape but you can stack arrays of same size and shape

In [85]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])


In [86]:
np.vstack((a,b))#it stacks arrays vertically

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [87]:
np.hstack((a,b))#it stacks arrays horizontally

array([1, 2, 3, 4, 5, 6, 7, 8])

In [88]:
np.column_stack((a,b))#it stacks arrays column wise

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### slicing of matrices

In [ ]:
c=np.arange(18).reshape(3,6)
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [91]:
np.hsplit(c,2)#it splits the matrix into 2 equal parts horizontally

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17]])]

### exercise

In [93]:
import numpy as np

In [94]:
##valid sudoku solution
sudoku=np.array([[5,3,4,6,7,8,9,1,2],
                 [6,7,2,1,9,5,3,4,8],
                 [1,9,8,3,4,2,5,6,7],
                 [8,5,9,7,6,1,4,2,3],
                 [4,2,6,8,5,3,7,9,1],
                 [7,1,3,9,2,4,8,5,6],
                 [9,6,1,5,3,7,2,8,4],
                 [2,8,7,4,1,9,6,3,5],
                 [3,4,5,2,8,6,1,7,9]])

In [95]:

a=np.sum(sudoku,axis=1)
a

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [96]:

b=np.sum(sudoku,axis=0)
b

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [ ]:
if np.all(a!=45) or np.all(b!=45):
    print("This is invalid sudoku")

else:print("This is valid sudoku")

This is valid sudoku


In [ ]:
def check_3x3_boxes(sudoku):
    for i in range(0,9,3):
        for j in range(0,9,3):
            box_sum=np.sum(sudoku[i:i+3,j:j+3])
            if box_sum!=45:
                print("invalid sudoku")
                break
    else:
        print("valid sudoku")
check_3x3_boxes(sudoku)


valid sudoku


### general question

In [100]:
import numpy as np
# columns:[Age,Math Marks,science marks]
data=np.array([[18,85,78], #1  student
               [19,92,88],#2  student
               [17,76,95],#3  student
               [18,65,70],#4  student
               [20,90,85]])#5  student

In [101]:
data.shape#this is an instance attribute so we dont need of braces

(5, 3)

In [102]:
np.mean(data[:,:1])

np.float64(18.4)

In [103]:
n=data[:,1:2]
n

array([[85],
       [92],
       [76],
       [65],
       [90]])

In [104]:
np.max(data[:,2:])

np.int64(95)

In [105]:
data[data[:,1]>=90]


array([[19, 92, 88],
       [20, 90, 85]])

In [106]:
n=data[data[0:,0]>19]
len(n)

1

In [107]:
data[:,1]+=5#no. of times you run no. of times add 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [108]:
np.mean(data[:,1])

np.float64(86.6)

In [109]:
np.mean(data[:,2])

np.float64(83.2)

In [110]:
data[(data[:,1]>=80)& (data[:,2]>=80)]


array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [111]:
data[data[:,2]<75, 2] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])