In [50]:
import numpy as np

In [51]:
print(np.__version__)

2.5.0


list v/s array

In [52]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10,0]
list1+list2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0]

In [53]:
a = np.array([1, 2, 3, 4,])
b = np.array([6, 7, 8, 9,])
a+b


array([ 7,  9, 11, 13])

priority 

In [54]:
# int+str-->str
# int+bool-->int
# int+float-->float

In [55]:
a=np.array([1,2,3,4,'5'])
b=np.array([6,7,8,9,'10'])
a+b


array(['16', '27', '38', '49', '510'], dtype='<U42')

In [56]:
a = np.array([1, 2, 3, True, 5])
b = np.array([6, 7, 8, False, "10"])
print(a)
print(b)


[1 2 3 1 5]
['6' '7' '8' 'False' '10']


Attributes of array

Dimensions of array


In [57]:
arr1=np.array([[10,20,30]])
arr2=np.array([[[100,20,]]])
print(arr1.ndim)  #No. of dimensions
print(arr2.ndim)

2
3


array creation methods

In [58]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [59]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [60]:
np.ones(4)

array([1., 1., 1., 1.])

In [61]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [62]:
np.full((3,2),3,str)

array([['3', '3'],
       ['3', '3'],
       ['3', '3']], dtype='<U1')

In [63]:
p=np.eye(4)
print(p)
print(p.ndim)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
2


In [64]:
np.eye(2,4,k=2,dtype=str)

array([['', '', '1', ''],
       ['', '', '', '1']], dtype='<U1')

 questions :
 
 what are the applications  of Eda

 what are  the difference b/w numpy , pandas,matplotlib and seaborn

 why numpy array is faster than list

 what are the diff methods of array creation

 what is the diff b/w list and array

In [65]:
np.array([1,2,3])




array([1, 2, 3])

In [66]:
np.arange(3, 10, 2)


array([3, 5, 7, 9])

In [67]:
np.eye(3, 2)#it form martrix with value=1 in diagonals


array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [68]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [69]:
np.arange(3)

array([0, 1, 2])

In [70]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [71]:
np.random.rand(10)

array([0.10275948, 0.12339428, 0.03164072, 0.56786019, 0.67111716,
       0.50646387, 0.81887726, 0.95130534, 0.98185621, 0.9189977 ])

In [72]:
np.random.randn(10)

array([-3.07503392,  0.99804375,  0.19493052,  1.2736641 ,  0.94545735,
        0.23485157,  1.66923006,  1.62336456,  0.81957272,  0.39270359])

In [73]:
np.identity(2)#it forms identity square matrix

array([[1., 0.],
       [0., 1.]])

In [74]:
a = np.array([[1, 2, 3, 4, 5],
              [5,6,7,8,9]])
np.diag(a)#it works on 1d and 2d only



array([1, 6])

In [75]:
b = np.array([1, 2, 3, 4, 5])
np.diag(b)
# converts 2d ino 1d and 1d into 2d


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [76]:
b=np.array([[[1,2,3],[4,5,6]],
             [[8,9,10],[11,12,13]]])
b.ndim


3

In [77]:
np.diagonal(b)#works with n dim array and return 1d array

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [78]:
np.full((2,3),4)

array([[4, 4, 4],
       [4, 4, 4]])

In [79]:
arr=np.array([[1,2,0],
              [4,5.2,6]],ndmin=2)
arr

array([[1. , 2. , 0. ],
       [4. , 5.2, 6. ]])

In [80]:
print(arr.size)

6


In [81]:
print(arr.shape)

(2, 3)


In [82]:
print(arr.dtype)

float64


In [83]:
print(arr.ndim)

2


In [84]:
arr.astype(bool)

array([[ True,  True, False],
       [ True,  True,  True]])

In [85]:
arr=np.array([1,2,3,4,5])
arr[0:3:2]

array([1, 3])

In [86]:
arr=np.diag([1,2,3,4,5,6])
arr

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [87]:
arr[3:,1:4]

array([[0, 0, 4],
       [0, 0, 0],
       [0, 0, 0]])

In [88]:
arr[:3,:3]

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [89]:
arr[:1,]

array([[1, 0, 0, 0, 0, 0]])

In [90]:
arr.shape

(6, 6)

In [91]:
arr.size

36

In [92]:
arr=np.arange(1,6)
arr

array([1, 2, 3, 4, 5])

In [93]:
arr[1:]

array([2, 3, 4, 5])

In [94]:
arr[-7:1]

array([1])

In [95]:
arr[::2]

array([1, 3, 5])

In [96]:
arr[1]

np.int64(2)

In [97]:
arr[10]

IndexError: index 10 is out of bounds for axis 0 with size 5

In [ ]:
arr[-1]

np.int64(5)

In [ ]:
arr[-8]

IndexError: index -8 is out of bounds for axis 0 with size 5

In [ ]:
arr=np.array([[1,2,3,4],
     [5,6,7,8],
     [9,10,11,12]])
print(arr.ndim)
arr.shape

(3, 4)

In [ ]:
arr[:,-2]

array([ 3,  7, 11])

In [ ]:
arr[1:3,-1:2:-1]

array([[ 8],
       [12]])

In [ ]:
arr=np.array([[[1,2,3],
              [4,5,6],
              [15,16,17]],
              [[7,8,9],
              [10,11,12],
              [13,14,15]]])
print(arr.ndim)
arr.shape

3


(2, 3, 3)

In [ ]:
arr[:,-1,-1:-3:-1]

array([[17, 16],
       [15, 14]])

In [ ]:
arr[:,1,:-3:-1]

array([[ 6,  5],
       [12, 11]])

In [ ]:
arr[:, 1, 1:]


array([[ 5,  6],
       [11, 12]])

In [ ]:
arr[1,1,1]#block:rows:columnsa

np.int64(11)

In [ ]:
arr[0,1,-2]

np.int64(5)

In [ ]:
#choose
arr=np.arange(1,5)
arr

array([1, 2, 3, 4])

In [ ]:
np.choose([0,1,0,0],arr)#for accessing a particular value multiple times

array([1, 2, 1, 1])

In [ ]:
choice=[0,1,0,2,3]#the size of array must equal to size of choice and all arrays must be of same size
arr1=np.arange(5,10)
arr2=np.arange(2,7)
arr3=np.arange(1,6)
arr4=np.arange(3,8)
print(arr1)
print(arr2)
print(arr3)
print(arr4)

[5 6 7 8 9]
[2 3 4 5 6]
[1 2 3 4 5]
[3 4 5 6 7]


In [ ]:
np.choose(choice,[arr1,arr2,arr3,arr4])#it is not possible to fetch value of same indexes from diff arrays

array([5, 3, 7, 4, 7])

In [ ]:
#insert
arr=np.array([10,20,30,40])
print(arr)
arr2=np.insert(arr,[3,1],[100,50])#shift elements
print(arr2)

[10 20 30 40]
[ 10  50  20  30 100  40]


In [ ]:
arr=np.arange(1,11,2)
print(arr)

[1 3 5 7 9]


In [ ]:
arr=np.arange(0,11).reshape(11,1)
arr

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [ ]:
arr=np.arange(1,50).reshape(7,7)
arr


array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [ ]:
arr=np.arange(1,11).reshape(2,5,1)
arr

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]])

In [ ]:
flat=arr.flatten()
flat[1]=1000
print(flat)#change in flat only
arr

[   1 1000    3    4    5    6    7    8    9   10]


array([[[  1],
        [100],
        [  3],
        [  4],
        [  5]],

       [[  6],
        [  7],
        [  8],
        [  9],
        [ 10]]])

In [ ]:
# raveled array
ravel=arr.ravel()
ravel[1]=100#change in both ravel arr
print(ravel)
arr

[  1 100   3   4   5   6   7   8   9  10]


array([[[  1],
        [100],
        [  3],
        [  4],
        [  5]],

       [[  6],
        [  7],
        [  8],
        [  9],
        [ 10]]])

In [ ]:
# Array equal
marks1=[80,90,70]
marks2=[80,90,70]
marks1==marks2

True

In [ ]:
n=np.array([marks1])
m=np.array([marks2])
np.equal(n,m)  # element by comparison

array([[ True,  True,  True]])

In [ ]:
n==m#element by comparison

array([[ True,  True,  True]])

In [ ]:
np.array_equal(n,m)#entire equality check karta h

True

In [ ]:
# Boolean indexing
marks=np.array([35,25,45,75,65])
marks[marks>=60]


array([75, 65])

In [ ]:
marks >= 60


array([False, False, False,  True,  True])

In [ ]:
~((marks >= 50) & (marks < 70))


array([ True,  True,  True,  True, False])

In [ ]:
marks[[False, False, False, False, True]]

array([65])

In [ ]:
marks[(marks>=50)&(marks<70)]

array([65])

In [ ]:
# fancy indexing
marks=np.array([35,80,45,90,60])
marks[[1,1,3]]

array([80, 80, 90])

In [ ]:
# argwhere
num=np.array([10,20,30,40,50])
print(np.argwhere(num>30))

[[3]
 [4]]


In [ ]:
# extract
np.extract(num>30,num)

array([40, 50])

In [98]:
# where
marks=np.array([10,20,30,40,50])
np.where(marks>40,"pass","fail")

array(['fail', 'fail', 'fail', 'fail', 'pass'], dtype='<U4')

In [ ]:
# take
np.take(arr,[1,2,3])

array([2, 3, 4])

In [99]:
np.put(marks,[1,2],[30,98])
marks

array([10, 30, 98, 40, 50])

In [ ]:
# concatenate
arr1=np.arange(11)
arr2=np.arange(11,31)
arr3=np.arange(5,1,-1)
arr4=np.concatenate((arr3,arr1,arr2))
arr4

array([ 5,  4,  3,  2,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
       13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
       30])

In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5, 6], [7, 8]])
arr=np.concatenate((arr1,arr2),axis=1)#column wise concaenate
arr

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=0)  # row wise concaenate
arr


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
# stacking array
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
arr3=np.array([[9,10],[11,12]])
arr=np.stack((arr1,arr2,arr3),axis=1)#dimension increases by 1
print(arr)

[[[ 1  2]
  [ 5  6]
  [ 9 10]]

 [[ 3  4]
  [ 7  8]
  [11 12]]]


In [ ]:
# stacking array
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])
arr = np.stack((arr1, arr2, arr3), axis=0)
print(arr)


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])
arr = np.vstack((arr1, arr2, arr3))
print(arr)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])
arr = np.hstack((arr1, arr2, arr3))
print(arr)


[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


In [ ]:
#split()method
arr=np.array([100,20,56,78,89,89])
print(np.split(arr,2))

[array([100,  20,  56]), array([78, 89, 89])]


In [ ]:
# array split
arr = np.array([1, 2, 4, 5, 12, 3, 4])
print(np.split(arr,4))


ValueError: array split does not result in an equal division

In [ ]:
#array split
arr=np.array([1,2,4,5,12,3,4])
print(np.array_split(arr,10))

[array([1]), array([2]), array([4]), array([5]), array([12]), array([3]), array([4]), array([], dtype=int64), array([], dtype=int64), array([], dtype=int64)]


In [ ]:
#append
arr=np.array([[1,2,3],
             [5,6,7]])
arr2=np.append(arr,4)
arr2

array([1, 2, 3, 5, 6, 7, 4])

In [ ]:
#insert
arr1=np.insert(arr,2,2)
arr1

array([1, 2, 2, 3, 5, 6, 7])

In [ ]:
arr1=np.array([12,23,34,45])
arr2=np.array([90,80,70,60])
arr=np.insert((arr1,arr2),4,[100])
arr

array([ 12,  23,  34,  45, 100,  90,  80,  70,  60])

In [ ]:
#delete
arr1 = np.array([[12, 23, 34, 45],[67,23,12,45]])
np.delete(arr1,(2,3),axis=1)

array([[12, 23],
       [67, 23]])

In [ ]:
#resize
arr1=np.linspace(1,10,5)
arr1

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
np.resize(arr1,3)

array([1.  , 3.25, 5.5 ])

In [ ]:
np.resize(arr1,9)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ,  1.  ,  3.25,  5.5 ,  7.75])

In [ ]:
# sort
arr1=np.arange(10,1,-1).reshape(3,3)
arr1.sort()
print(arr1)

[[ 8  9 10]
 [ 5  6  7]
 [ 2  3  4]]


In [ ]:
arr1 = np.arange(10, 1, -1)
arr1.sort()
print(arr1)

[ 2  3  4  5  6  7  8  9 10]


In [ ]:
# argsort
arr2=np.array([3,2,0,2,7,4])

In [ ]:
np.argsort(arr2)#returns the index that would sort the array

array([2, 1, 3, 0, 5, 4])

In [ ]:
# unique
arr=np.array([1,2,3,4,5,12,32,1,2])
print(np.unique(arr))

[ 1  2  3  4  5 12 32]


In [ ]:
# flip-->reverse the array
np.flip(arr)

array([ 2,  1, 32, 12,  5,  4,  3,  2,  1])

In [ ]:
arr1=np.array([1,2,3,4,5,6])
arr2=np.array([1,2,3,4,5,6])[::-1]
print(arr1)
print(arr2)

[1 2 3 4 5 6]
[6 5 4 3 2 1]


In [ ]:
np.add(arr1,arr2)

array([7, 7, 7, 7, 7, 7])

In [ ]:
np.subtract(arr2,arr1)

array([ 5,  3,  1, -1, -3, -5])

In [ ]:
np.multiply(arr1,arr2)

array([ 6, 10, 12, 12, 10,  6])

In [ ]:
np.divide(arr1,arr2)

array([0.16666667, 0.4       , 0.75      , 1.33333333, 2.5       ,
       6.        ])

In [ ]:
np.power(arr1,arr2)

array([ 1, 32, 81, 64, 25,  6])

In [ ]:
np.log(2)#e=2.718

np.float64(0.6931471805599453)

In [ ]:
np.mod(arr1,arr2)

array([1, 2, 3, 1, 1, 0])

In [ ]:
np.maximum(arr1,arr2)

array([6, 5, 4, 4, 5, 6])

In [ ]:
np.minimum(arr1,arr2)

array([1, 2, 3, 3, 2, 1])

In [ ]:
np.log10(2)

np.float64(0.3010299956639812)

In [ ]:
np.sin(np.pi/2)

np.float64(1.0)

In [ ]:
np.pi

3.141592653589793

In [ ]:
np.round(2.1)

np.float64(2.0)

In [ ]:
np.round(2.8)

np.float64(3.0)

In [ ]:
np.ceil(2.9)

np.float64(3.0)

In [ ]:
np.floor(2.9)

np.float64(2.0)

In [ ]:
np.sin(np.pi/2)

np.float64(1.0)

In [ ]:
np.sqrt(99)

np.float64(9.9498743710662)

In [ ]:
a=np.log(10)#e:2.718

In [ ]:
2.718**a

np.float64(9.997612866396764)

In [ ]:
np.log2(4)

np.float64(2.0)

In [ ]:
np.floor(10.1)

np.float64(10.0)

In [ ]:
np.floor(1.9)

np.float64(1.0)

In [ ]:
np.round(2.51)

np.float64(3.0)

In [ ]:
np.round(3.5)

np.float64(4.0)

In [ ]:
np.round(4.5)

np.float64(4.0)

In [ ]:
np.round(2.5)

np.float64(2.0)

In [ ]:
arr1=np.arange(11,21)
arr1

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
np.mean(arr1)

np.float64(15.5)

In [ ]:
arr1 = np.array([11, 21,3,22])
arr2= np.array([1,2,3,4])

arr1


array([11, 21,  3, 22])

In [ ]:
np.median(arr1)

np.float64(16.0)

In [ ]:
np.std(arr1)

np.float64(7.790218225441442)

In [ ]:
np.var(arr1)

np.float64(60.6875)

In [ ]:
np.prod(arr1)

np.int64(15246)

In [ ]:
np.min(arr1)

np.int64(3)

In [ ]:
np.argmin(arr1)

np.int64(2)

In [ ]:
np.argmax(arr1)

np.int64(3)

In [ ]:
np.sum(arr1)

np.int64(57)

In [ ]:
arr1 = np.array([11, 2, 3, 2])
arr2 = np.array([1, 2, 3, 4])


In [ ]:
np.dot(arr1,arr2)

np.int64(32)

In [ ]:
arr1=np.array([1,2,3,0,4])

In [ ]:
np.var(arr1)

np.float64(2.0)

In [ ]:
arr1 = np.array([[[11, 2, 3],[1,2,3]]])
arr2 = np.array([[[1, 2, 3],[1,2,3]]])


In [ ]:
np.cross(arr1,arr2)

array([[[  0, -30,  20],
        [  0,   0,   0]]])

In [ ]:
# random module

In [ ]:
n=np.random.rand()
np.round(n,2)

np.float64(0.46)

In [ ]:
n=np.random.rand(4)
n

array([0.14675589, 0.09233859, 0.18626021, 0.34556073])

In [ ]:
np.random.seed(2)
np.random.rand(1)



array([0.4359949])

In [ ]:
np.random.rand(4)

array([0.24010282, 0.98317239, 0.31563279, 0.75247818])

In [ ]:
arr=np.random.randn(6)
arr

array([-0.02454096,  0.76651986,  0.17665025, -0.87503774,  0.41987015,
       -0.70543696])

In [ ]:
np.mean(arr)

np.float64(-0.04032923319568968)

In [ ]:
arr=np.random.randint(1,10,5)#Last is not included
arr

array([7, 7, 7, 1, 7], dtype=int32)

In [ ]:
np.random.choice(arr,2)

array([7, 7], dtype=int32)

In [ ]:
np.random.choice(arr, 10)


array([7, 7, 1, 7, 7, 7, 7, 1, 7, 7], dtype=int32)

In [ ]:
np.random.shuffle(arr)# change appears in original array

In [ ]:
arr

array([7, 7, 1, 7, 7], dtype=int32)

In [ ]:
print(np.random.permutation(arr))#original array doesnot change
arr

[7 1 7 7 7]


array([7, 7, 1, 7, 7], dtype=int32)

In [ ]:
arr1=np.array([1,2,3,4])
arr1*2

array([3, 4, 5, 6])

In [ ]:
arr1=np.array([1,2,3,4])

arr1*2

array([2, 4, 6, 8])

In [107]:
arr=np.zeros((8,8),int)
arr[1::2,::2]=1
arr[::2,1::2]=1
arr


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [109]:
x=np.array([21,64,86,22,74,55,81,79,90,89])
y=np.array([21,7,3,45,10,29,55,4,37,18])
np.where(x>y)
np.where(x==y)

(array([0]),)

In [112]:
arr=np.ones((8,8),int)
arr[::2,::2]=0
arr[1::2,1::2]=0
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [134]:
arr=np.zeros((5,5),int)
arr[1:-1, 1:-1]=1
arr

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 1, 1, 1, 0],
       [0, 0, 0, 0, 0]])

In [137]:
arr=np.zeros((5,5))
arr[1:-1,1:-1]=1
arr

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [144]:
arr=np.zeros((8,8),int)
arr[[0,-1],:]=1
arr[:,[0,-1]]=1
arr

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1]])